######################################################################
# Automatically generated by qmake (2.01a) gio feb 17 23:35:57 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

CONFIG += link_pkgconfig

PKGCONFIG += telepathy-logger-0.1 telepathy-glib glib-2.0

# Input
HEADERS += query-log.h
SOURCES += query-log.cpp dummy-main.cpp
